export {Text, View, Platform, TextInput, Button, Image,StyleSheet, ScrollView} from 'react-native';
export {default as FontAwesome6} from '@expo/vector-icons/FontAwesome6';
export {default as FontAwesome5} from '@expo/vector-icons/FontAwesome5';
export {default as MaterialCommunityIcons} from '@expo/vector-icons/MaterialCommunityIcons';
export {default as AntDesign} from '@expo/vector-icons/AntDesign';
export {default as Ionicons} from "@expo/vector-icons/Ionicons";
export {default as React} from 'react';
export {SafeAreaView} from 'react-native-safe-area-context';
export { styles, globalStyles } from '../styles/styles';
export {default as Logo} from '../components/logo';
export { Background } from '@react-navigation/elements';
export { Tabs } from 'expo-router';
